package com.vytsablinskas.flavorfare.integration.services;

import com.vytsablinskas.flavorfare.business.exceptions.ResourceNotFoundException;
import com.vytsablinskas.flavorfare.business.services.interfaces.RestaurantService;
import com.vytsablinskas.flavorfare.shared.dtos.restaurant.AddRestaurantDto;
import com.vytsablinskas.flavorfare.shared.dtos.restaurant.RestaurantDto;
import com.vytsablinskas.flavorfare.shared.dtos.restaurant.UpdateRestaurantDto;
import com.vytsablinskas.flavorfare.utils.RestaurantTestData;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ExtendWith(SpringExtension.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class RestaurantServiceIntegrationTests {
    private final RestaurantService underTest;

    @Autowired
    public RestaurantServiceIntegrationTests(RestaurantService underTest) {
        this.underTest = underTest;
    }

    @Test
    public void getRestaurants_shouldGetAllRestaurants() {
        AddRestaurantDto restaurantA = RestaurantTestData.getAddRestaurantDtoA();
        underTest.addRestaurant(restaurantA);

        AddRestaurantDto addRestaurantDtoB = RestaurantTestData.getAddRestaurantDtoB();
        underTest.addRestaurant(addRestaurantDtoB);

        List<RestaurantDto> restaurants = underTest.getRestaurants();

        assertThat(restaurants)
                .hasSize(2);
    }

    @Test
    public void getRestaurant_validId_returnsRestaurantDto() {
        AddRestaurantDto addRestaurantDtoA = RestaurantTestData.getAddRestaurantDtoA();
        RestaurantDto restaurantDto = underTest.addRestaurant(addRestaurantDtoA);

        RestaurantDto result = underTest.getRestaurant(restaurantDto.getId());

        assertThat(result)
                .isNotNull()
                .isEqualTo(restaurantDto);
    }

    @Test
    public void getRestaurant_invalidId_returnsThrowResourceNotFoundException() {
        Assertions.assertThatThrownBy(() -> underTest.getRestaurant(1))
                .isInstanceOf(ResourceNotFoundException.class);
    }

    @Test
    public void addRestaurant_shouldAddRestaurantWithAutoGeneratedId() {
        AddRestaurantDto restaurantA = RestaurantTestData.getAddRestaurantDtoA();

        RestaurantDto createdRestaurant = underTest.addRestaurant(restaurantA);

        assertThat(createdRestaurant.getId()).isGreaterThan(0);
    }

    @Test
    public void updateRestaurant_validId_shouldUpdateAndReturnUpdatedRestaurant() {
        AddRestaurantDto restaurantA = RestaurantTestData.getAddRestaurantDtoA();
        RestaurantDto createdRestaurant = underTest.addRestaurant(restaurantA);
        UpdateRestaurantDto restaurantUpdateDto = RestaurantTestData.getUpdateRestaurantDtoA();

        RestaurantDto result = underTest.updateRestaurant(createdRestaurant.getId(), restaurantUpdateDto);
        assertThat(result.getName()).isEqualTo(restaurantUpdateDto.getName());
    }

    @Test
    public void updateRestaurant_invalidId_shouldThrowResourceNotFoundException() {
        UpdateRestaurantDto restaurantUpdateDto = RestaurantTestData.getUpdateRestaurantDtoA();

        Assertions.assertThatThrownBy(() -> underTest.updateRestaurant(1, restaurantUpdateDto))
                .isInstanceOf(ResourceNotFoundException.class);
    }

    @Test
    public void deleteRestaurant_validId_shouldDeleteRestaurant() {
        AddRestaurantDto addRestaurantDtoA = RestaurantTestData.getAddRestaurantDtoA();
        RestaurantDto createdRestaurantA = underTest.addRestaurant(addRestaurantDtoA);

        underTest.deleteRestaurant(createdRestaurantA.getId());
        List<RestaurantDto> restaurants = underTest.getRestaurants();

        assertThat(restaurants).hasSize(0);
    }

    @Test
    public void deleteRestaurant_invalidId_shouldThrowResourceNotFoundException() {
        Integer invalidId = 1;

        Assertions.assertThatThrownBy(() -> underTest.getRestaurant(invalidId))
                .isInstanceOf(ResourceNotFoundException.class);
    }
}